language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source
    - composer create-project nette/code-checker code-checker 2.5 --no-interaction --prefer-source

script:
    - php code-checker/src/code-checker.php --short-arrays -d src/
    - vendor/bin/phpcs --standard=codesniffer.xml --warning-severity=0 src/
